#!/usr/bin/env python
# -*- coding: utf-8 -*-

# This file is part of global_sewage_signatures.
# https://github.com/josl/Global_Sewage_Signatures

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2016, Jose L. Bellod Cisneros & Kosai Al-Nakked
# <bellod.cisneros@gmail.com & kosai@cbs.dtu.dk>

global_sewage_app:
    build: .
    # command: redis-server ./redis.conf
    volumes:
        - $PWD/database/redis:/data
        - $PWD/database:/usr/data
    ports:
        - "4444:4444"
