#!/usr/bin/env python
# -*- coding: utf-8 -*-

# This file is part of global_sewage_signatures.
# https://github.com/josl/Global_Sewage_Signatures

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2016, Jose L. Bellod Cisneros & Kosai Al-Nakked
# <bellod.cisneros@gmail.com & kosai@cbs.dtu.dk>
version: '2.1'

services:
    global_sewage_app:
        build: .
        command: bash
        volumes:
            - $PWD:/usr/src
    redis:
        image: redis
        volumes:
            - $PWD/database/redis:/data
        ports:
            - "6379:6379"
