#!/usr/bin/env python
# -*- coding: utf-8 -*-

# This file is part of global_sewage_signatures.
# https://github.com/josl/Global_Sewage_Signatures

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2016, Jose L. Bellod Cisneros & Kosai Al-Nakked
# <bellod.cisneros@gmail.com & kosai@cbs.dtu.dk>

version: '2'
services:
    sewage_app:
        container_name: sewage_app
        build: .
        command: /bin/bash
        volumes:
            - $PWD:/usr/src
        depends_on:
            - redis
        stdin_open: true
        tty: true
    redis:
        container_name: sewage_redis
        command: redis-server --appendonly yes
        image: redis:latest
        volumes:
            - $PWD/database/redis:/data
        ports:
            - "6379:6379"
